# Yes hello this is MinoDuel config file
# Most stuff is editable in-game, so there is no need to edit this. oke?
# If you don't see anything in here, don't worry. It will be generated upon startup.

# Teleport delay in seconds
tp-delay-seconds: 3

# Check all dropped items for MinoDuel kit markers and remove found items
# Do not enable this if you are absolutely certain that items have been
# leaked from the closed arena environment.
# Please, do not forget to disable it once you're done.
find-item-markers: false
