# Yes hello this is 1vs1 config file
# Most stuff is editable in-game, so there is no need to edit this. oke?
# If you don't see anything in here, don't worry. It will be generated upon startup.

# Teleport delay in seconds
tp-delay-seconds: 3
